#!/bin/sh -e

if [ -f /var/lib/games/thrust.highscore ]
then
    if [ -f /var/games/thrust.highscore ]
    then
	echo "Saving the new highscores for you to /var/games/thrust/highscore.new"
	mv /var/games/thrust.highscore /var/games/thrust.highscore.new	
    fi
    echo Moving the old highscore file to the new place
    mv /var/lib/games/thrust.highscore /var/games/thrust.highscore
fi

# Create a high score file.
touch /var/games/thrust.highscore
# Always fix permissions, because an old version of the package got them 
# wrong.
chown root.games /var/games/thrust.highscore
chmod 664 /var/games/thrust.highscore

#DEBHELPER#
